create type "public"."SCREENS" as enum ('lock', 'home', 'messages', 'chat');

create table "public"."apps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "opens" text default ''::text,
    "icon_url" text default ''::text,
    "app_title" text default ''::text
);


alter table "public"."apps" enable row level security;

create table "public"."favorite_apps" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "opens" text default ''::text,
    "icon_url" text default ''::text,
    "app_title" text default ''::text
);


alter table "public"."favorite_apps" enable row level security;

create table "public"."screens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "screen_name" "SCREENS" not null default 'lock'::"SCREENS"
);


alter table "public"."screens" enable row level security;

CREATE UNIQUE INDEX apps_pkey ON public.apps USING btree (id);

CREATE UNIQUE INDEX favorite_apps_pkey ON public.favorite_apps USING btree (id);

CREATE UNIQUE INDEX screens_pkey ON public.screens USING btree (id);

alter table "public"."apps" add constraint "apps_pkey" PRIMARY KEY using index "apps_pkey";

alter table "public"."favorite_apps" add constraint "favorite_apps_pkey" PRIMARY KEY using index "favorite_apps_pkey";

alter table "public"."screens" add constraint "screens_pkey" PRIMARY KEY using index "screens_pkey";

grant delete on table "public"."apps" to "anon";

grant insert on table "public"."apps" to "anon";

grant references on table "public"."apps" to "anon";

grant select on table "public"."apps" to "anon";

grant trigger on table "public"."apps" to "anon";

grant truncate on table "public"."apps" to "anon";

grant update on table "public"."apps" to "anon";

grant delete on table "public"."apps" to "authenticated";

grant insert on table "public"."apps" to "authenticated";

grant references on table "public"."apps" to "authenticated";

grant select on table "public"."apps" to "authenticated";

grant trigger on table "public"."apps" to "authenticated";

grant truncate on table "public"."apps" to "authenticated";

grant update on table "public"."apps" to "authenticated";

grant delete on table "public"."apps" to "service_role";

grant insert on table "public"."apps" to "service_role";

grant references on table "public"."apps" to "service_role";

grant select on table "public"."apps" to "service_role";

grant trigger on table "public"."apps" to "service_role";

grant truncate on table "public"."apps" to "service_role";

grant update on table "public"."apps" to "service_role";

grant delete on table "public"."favorite_apps" to "anon";

grant insert on table "public"."favorite_apps" to "anon";

grant references on table "public"."favorite_apps" to "anon";

grant select on table "public"."favorite_apps" to "anon";

grant trigger on table "public"."favorite_apps" to "anon";

grant truncate on table "public"."favorite_apps" to "anon";

grant update on table "public"."favorite_apps" to "anon";

grant delete on table "public"."favorite_apps" to "authenticated";

grant insert on table "public"."favorite_apps" to "authenticated";

grant references on table "public"."favorite_apps" to "authenticated";

grant select on table "public"."favorite_apps" to "authenticated";

grant trigger on table "public"."favorite_apps" to "authenticated";

grant truncate on table "public"."favorite_apps" to "authenticated";

grant update on table "public"."favorite_apps" to "authenticated";

grant delete on table "public"."favorite_apps" to "service_role";

grant insert on table "public"."favorite_apps" to "service_role";

grant references on table "public"."favorite_apps" to "service_role";

grant select on table "public"."favorite_apps" to "service_role";

grant trigger on table "public"."favorite_apps" to "service_role";

grant truncate on table "public"."favorite_apps" to "service_role";

grant update on table "public"."favorite_apps" to "service_role";

grant delete on table "public"."screens" to "anon";

grant insert on table "public"."screens" to "anon";

grant references on table "public"."screens" to "anon";

grant select on table "public"."screens" to "anon";

grant trigger on table "public"."screens" to "anon";

grant truncate on table "public"."screens" to "anon";

grant update on table "public"."screens" to "anon";

grant delete on table "public"."screens" to "authenticated";

grant insert on table "public"."screens" to "authenticated";

grant references on table "public"."screens" to "authenticated";

grant select on table "public"."screens" to "authenticated";

grant trigger on table "public"."screens" to "authenticated";

grant truncate on table "public"."screens" to "authenticated";

grant update on table "public"."screens" to "authenticated";

grant delete on table "public"."screens" to "service_role";

grant insert on table "public"."screens" to "service_role";

grant references on table "public"."screens" to "service_role";

grant select on table "public"."screens" to "service_role";

grant trigger on table "public"."screens" to "service_role";

grant truncate on table "public"."screens" to "service_role";

grant update on table "public"."screens" to "service_role";

create policy "Enable read access for all users"
on "public"."apps"
as permissive
for select
to anon
using (true);



